In [ ]:
import numpy as np
import cv2 as cv
import matplotlib.pyplot as plt


ojos = cv.imread('eyes.jpg', cv.IMREAD_COLOR)
gray = cv.cvtColor(ojos, cv.COLOR_BGR2GRAY)
ojos_blur = cv.medianBlur(gray, 5)


# parametros 
method = cv.HOUGH_GRADIENT
dp = 1 # resolucion del acumulador igual a la de la imagen
minDist = 0.01 # distancia minima entre centros de los circulos
param1 = 140 # el maximo umbral del detector de Canny
param2 = 30 # umbral del acumulador del detector de centros
minRadius = 7 # radio minimo 
maxRadius = 35 # radio maximo

circles = cv.HoughCircles(ojos_blur, method, dp, minDist, param1=param1, param2=param2, minRadius=minRadius, maxRadius=maxRadius)
print(circles)
if circles is not None:
    circles = np.uint16(np.around(circles))
    for i in circles[0, :]:
        # perimetro
        cv.circle(ojos, (i[0], i[1]), i[2], (0, 255, 0), 2)
        # centro
        cv.circle(ojos, (i[0], i[1]), 2, (0, 0, 255), 3)

cv.imshow('Iris detectado',ojos)
cv.waitKey(0)
cv.destroyAllWindows()

[[[461.5 181.5  30.9]
  [143.5 188.5  32.2]
  [464.5 514.5  31.9]
  [138.5 295.5  29.9]
  [463.5 511.5  34.4]
  [460.5 180.5  32.1]
  [144.5 187.5  33.3]
  [464.5 418.5  30.6]
  [448.5 291.5  32.2]
  [142.5 187.5  33.2]
  [457.5  80.5  27.4]
  [464.5 416.5  32. ]
  [132.5 413.5  30. ]
  [129.5 505.5  31.1]
  [447.5 292.5  31.1]
  [146.5 191.5  28.7]
  [462.5 512.5  34.4]
  [132.5 505.5  13.4]
  [131.5 418.5  25.2]
  [463.5 515.5  11.8]
  [454.5  79.5  11.6]
  [445.5 295.5   9.4]
  [133.5 507.5  13.2]
  [462.5 417.5  12.2]
  [134.5 413.5  10.6]
  [150.5  79.5  10.6]
  [136.5 412.5  13. ]]]
